FROM maven:3.9-eclipse-temurin-17

WORKDIR /app

# Instala dependências Maven (cache)
COPY pom.xml .
COPY mvnw .
COPY .mvn .mvn
RUN mvn dependency:go-offline

# Copia todo o código
COPY . .

EXPOSE 8080

# Comando para desenvolvimento (hot reload)
CMD ["./mvnw", "spring-boot:run"]
